Connecting to server on port 3001...
Connected to server on port 3001
Something went wrong running your bot: unhashable type: 'Plane'
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 50, in steer_input
closest_plane[plane] = None
~~~~~~~~~~~~~^^^^^^^
TypeError: unhashable type: 'Plane'
Something went wrong running your bot: unhashable type: 'Plane'
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 50, in steer_input
closest_plane[plane] = None
~~~~~~~~~~~~~^^^^^^^
TypeError: unhashable type: 'Plane'
Something went wrong running your bot: unhashable type: 'Plane'
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 50, in steer_input
closest_plane[plane] = None
~~~~~~~~~~~~~^^^^^^^
TypeError: unhashable type: 'Plane'
Your bot failed to respond 3 times in a row (is your bot broken?) and was disconnected