Connecting to server on port 3001...
Connected to server on port 3001
Something went wrong running your bot: not all arguments converted during string formatting
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 57, in steer_input
if (id % 2) == 0:
~~~^~~
TypeError: not all arguments converted during string formatting
Something went wrong running your bot: not all arguments converted during string formatting
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 57, in steer_input
if (id % 2) == 0:
~~~^~~
TypeError: not all arguments converted during string formatting
Something went wrong running your bot: not all arguments converted during string formatting
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 57, in steer_input
if (id % 2) == 0:
~~~^~~
TypeError: not all arguments converted during string formatting
Your bot failed to respond 3 times in a row (is your bot broken?) and was disconnected